/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lanrhyme_micyou_audio_WasapiLoopbackNative */

#ifndef _Included_com_lanrhyme_micyou_audio_WasapiLoopbackNative
#define _Included_com_lanrhyme_micyou_audio_WasapiLoopbackNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lanrhyme_micyou_audio_WasapiLoopbackNative
 * Method:    nativeStart
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lanrhyme_micyou_audio_WasapiLoopbackNative_nativeStart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lanrhyme_micyou_audio_WasapiLoopbackNative
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lanrhyme_micyou_audio_WasapiLoopbackNative_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
