blank_issues_enabled: false
contact_links:
  - name: "使用指南 / FAQ"
    url: "https://github.com/LanRhyme/MicYou/blob/master/docs/FAQ.md"
    about: "在报告问题前，请先查阅使用指南和常见问题解答"

  - name: "最新版本下载"
    url: "https://github.com/LanRhyme/MicYou/releases/latest"
    about: "我们只处理最新版本的问题，请先确认您使用的是最新版"
