[package]
name = "micyou-tui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "MicYou interactive terminal interface"

[[bin]]
name = "micyou-tui"
path = "src/main.rs"

[dependencies]
micyou-core = { workspace = true, features = ["headless-host", "vbcable", "web-server"] }

clap.workspace = true
serde_json.workspace = true
crossterm = "0.28.1"
ratatui = "0.29.0"
sysinfo = "0.39.6"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tauri-winres.workspace = true
