[package]
name = "micyou-app"
version = "2.0.3"
description = "MicYou - Turn your Android device into a high-quality PC microphone"
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "micyou"
path = "src/main.rs"

[features]
default = ["vbcable", "web-server"]
vbcable = ["micyou-core/vbcable"]
web-server = ["micyou-core/web-server"]

[dependencies]
micyou-core.workspace = true

tauri = { version = "2", features = [
  "macos-private-api",
  "tray-icon",
  "image-png",
] }
tauri-plugin-autostart = "2"
tauri-plugin-dialog = "2.7.1"
tauri-plugin-global-shortcut = "2"
tauri-plugin-log = "2.8.0"
tauri-plugin-notification = "2.3.3"
tauri-plugin-opener = "2"

log.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18", default-features = false }
glib = "0.18"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
window-vibrancy = "0.7"
